# Generated by Django 5.2.7 on 2025-10-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contenuto',
            new_name='descrizione',
        ),
    ]
